# Generated by Django 5.2.10 on 2026-01-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='is_reminder_enabled',
            field=models.BooleanField(default=False, help_text='Включить напоминание через Telegram'),
        ),
    ]
