# Generated by Django 5.2.10 on 2026-01-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_habit_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='next_reminder',
            field=models.DateTimeField(blank=True, help_text='Следующее напоминание (UTC)', null=True),
        ),
    ]
